---
abstract: 'Perl 6 documentation reader'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Script: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: grok
no_index:
  directory:
    - inc
    - share
    - t
    - t_source
requires:
  File::ShareDir: 0
  File::Temp: 0
  Getopt::Long: 2.33
  IO::Interactive: 0
  Perl6::Perldoc: 0.0.5
  Perl6::Perldoc::To::Ansi: 0.03
  Pod::Usage: 0
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.06
