---
abstract: 'Perl 6 documentation reader'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Test::More: 0
  Test::Script: 0
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: grok
no_index:
  directory:
    - inc
    - t
    - t_source
requires:
  Getopt::Long: 2.33
  Perl6::Perldoc: 0.0.5
  Perl6::Perldoc::To::Ansi: 0.01
  Pod::Usage: 0
  perl: 5.6.0
version: 0.03
